// Generated by CoffeeScript 1.7.1
// ==UserScript==
// @name					Blue Light Filter
// @namespace				lkytal
// @author					lkytal
// @homepage				http://coldfire.qiniudn.com/
// @icon					http://lkytal.qiniudn.com/ic.ico
// @version					1.0.2
// @description				减低页面的亮度，快捷键：Alt+上/下调节亮度，Alt+F5开关遮罩
// @include					*
// @grant					GM_addStyle
// @grant					unsafeWindow
// @grant					GM_getValue
// @grant					GM_setValue
// @homepageURL				https://git.oschina.net/coldfire/GM
// @updateURL				https://git.oschina.net/coldfire/GM/raw/master/meta/color.meta.js
// @downloadURL				https://git.oschina.net/coldfire/GM/raw/master/color.user.js
// ==/UserScript==