// Generated by IcedCoffeeScript 1.7.1-e
// ==UserScript==
// @name					Text To link
// @description				把文字链接转换为可点击链接
// @author					lkytal
// @namespace				Lkytal
// @homepage				http://coldfire.qiniudn.com/
// @include					*
// @exclude					*pan.baidu.com/*
// @exclude					*renren.com/*
// @exclude					*exhentai.org/*
// @version					2.5.2
// @icon					http://lkytal.qiniudn.com/ic.ico
// @grant					unsafeWindow
// @homepageURL				https://git.oschina.net/coldfire/GM
// @updateURL				https://git.oschina.net/coldfire/GM/raw/master/linkMix.user.js
// @downloadURL				https://git.oschina.net/coldfire/GM/raw/master/linkMix.user.js
// ==/UserScript==