// Generated by CoffeeScript 1.7.1
// ==UserScript==
// @name						Tieba Enhance
// @namespace					lkytal
// @author						lkytal
// @description					Multiply Enhance for tieba
// @include						http://tieba.baidu.com/*
// @include						https://tieba.baidu.com/*
// @version						5.8.6
// @author						lkytal
// @require						http://code.jquery.com/jquery-2.1.1.min.js
// @icon						http://lkytal.qiniudn.com/ic.ico
// @grant						unsafeWindow
// @grant						GM_addStyle
// @grant						GM_xmlhttpRequest
// @grant						GM_getValue
// @grant						GM_setValue
// @grant						GM_listValues
// @grant						GM_deleteValue
// @homepageURL					https://git.oschina.net/coldfire/GM
// @updateURL					https://git.oschina.net/coldfire/GM/raw/master/meta/tieba_enhance.meta.js
// @downloadURL					https://git.oschina.net/coldfire/GM/raw/master/tieba_enhance.user.js
// ==/UserScript==